name = "masuda-bot"
main = "src/index.ts"
compatibility_date = "2025-01-29"

[observability.logs]
enabled = true

[triggers]
crons =  ["*/1 * * * *"]

[vars]
MASUDA_URL = "https://anond.hatelabo.jp/rss"
MISSKEY_HOST = "jiskey.dev"
MISSKEY_TOKEN = "API_TOKEN"
